import {library} from '@fortawesome/fontawesome-svg-core'
import {
  faUser,
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faArrowUp,
  faArrowDown,
  faExpand,
  faCompress,
  faBolt,
  faSpinner,
  faWrench,
  faLightbulb,
  faRightLeft,
  faHelmetSafety,
  faHandHoldingHeart,
  faShield,
  faMessage,
  faLegal,
  faAnchor,
} from '@fortawesome/free-solid-svg-icons'

import {
  faFacebookSquare,
  faTwitter,
  faLinkedin,
  faSkype,
  faGoogle,
  faInstagram,
  faYoutube,
  faWhatsapp,
} from '@fortawesome/free-brands-svg-icons'

library.add(
  faAnchor,
  faLegal,
  faShield,
  faMessage,
  faHandHoldingHeart,
  faHelmetSafety,
  faRightLeft,
  faLightbulb,
  faUser,
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faArrowUp,
  faArrowDown,
  faExpand,
  faCompress,
  faBolt,
  faSpinner,
  faFacebookSquare,
  faTwitter,
  faLinkedin,
  faSkype,
  faGoogle,
  faInstagram,
  faYoutube,
  faWhatsapp,
  faWrench
)